version: '3.8'

services:
  discovery-server:
    build:
      context: .
      dockerfile: retail-banking-discovery-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - retail-banking-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-gateway:
    build:
      context: .
      dockerfile: retail-banking-api-gateway/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - retail-banking-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  account-service:
    build:
      context: .
      dockerfile: retail-banking-account-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      discovery-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/retail_banking?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - retail-banking-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  number-service:
    build:
      context: .
      dockerfile: retail-banking-number-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - retail-banking-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=retail_banking
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - retail-banking-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  retail-banking-network:
    driver: bridge

volumes:
  mysql_data: 