version: '3.8'

services:
  discovery-server:
    build:
      context: .
      dockerfile: retail-banking-discovery-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - retail-banking-network

  api-gateway:
    build:
      context: .
      dockerfile: retail-banking-api-gateway/Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - discovery-server
    networks:
      - retail-banking-network

  account-service:
    build:
      context: .
      dockerfile: retail-banking-account-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/retail_banking?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - retail-banking-network

  number-service:
    build:
      context: .
      dockerfile: retail-banking-number-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
    networks:
      - retail-banking-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=retail_banking
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - retail-banking-network

networks:
  retail-banking-network:
    driver: bridge

volumes:
  mysql_data: 