spring:
  application:
    name: retail-banking-exception-handling-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    discovery:
      enabled: true
  jackson:
    default-property-inclusion: non_null

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: DEBUG
    com.retail.banking: DEBUG 