spring:
  application:
    name: retail-banking-account-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    discovery:
      enabled: true
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://mysql:3306/retail_banking?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: DEBUG
    com.retail.banking: DEBUG

fakestore:
  api:
    base-url: https://fakestoreapi.com 