spring:
  application:
    name: retail-banking-api-gateway
  cloud:
    gateway:
      routes:
        - id: fakestore-service
          uri: lb://retail-banking-account-service
          predicates:
            - Path=/api/fakestore/**
          filters:
            - StripPrefix=1
        - id: account-service
          uri: lb://retail-banking-account-service
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - StripPrefix=2
        - id: http-client-service
          uri: lb://retail-banking-http-client-service
          predicates:
            - Path=/api/v1/http-client/**
          filters:
            - StripPrefix=2
        - id: soap-client-service
          uri: lb://retail-banking-soap-client-service
          predicates:
            - Path=/api/v1/soap-client/**
          filters:
            - StripPrefix=2
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    user:
      name: admin
      password: admin

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG 