spring:
  application:
    name: retail-banking-number-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
    com.retail.banking: DEBUG

soap:
  service:
    url: https://www.dataaccess.com/webservicesserver/NumberConversion.wso 