
package com.retail.banking.soap.client.wsdl;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "NumberConversionSoapType", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NumberConversionSoapType {


    /**
     * 
     * @param ubiNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NumberToWords", action = "http://www.dataaccess.com/webservicesserver/NumberToWords")
    @WebResult(name = "NumberToWordsResult", targetNamespace = "")
    @RequestWrapper(localName = "NumberToWords", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.retail.banking.soap.client.wsdl.NumberToWords")
    @ResponseWrapper(localName = "NumberToWordsResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.retail.banking.soap.client.wsdl.NumberToWordsResponse")
    public String numberToWords(
        @WebParam(name = "ubiNum", targetNamespace = "")
        BigInteger ubiNum);

    /**
     * 
     * @param dNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NumberToDollars", action = "http://www.dataaccess.com/webservicesserver/NumberToDollars")
    @WebResult(name = "NumberToDollarsResult", targetNamespace = "")
    @RequestWrapper(localName = "NumberToDollars", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.retail.banking.soap.client.wsdl.NumberToDollars")
    @ResponseWrapper(localName = "NumberToDollarsResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.retail.banking.soap.client.wsdl.NumberToDollarsResponse")
    public String numberToDollars(
        @WebParam(name = "dNum", targetNamespace = "")
        BigDecimal dNum);

}
